// Nutrify Mock Data

import { Food, Exercise, Workout, Challenge } from './types';

export const mockFoods: Food[] = [
  {
    id: '1',
    name: 'Banana',
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12.2,
    sodium: 1,
    servingSize: 100,
    servingUnit: 'g',
    category: 'Frutas',
    isUltraProcessed: false,
    score: 85,
    grade: 'A',
  },
  {
    id: '2',
    name: 'Peito de Frango Grelhado',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 74,
    servingSize: 100,
    servingUnit: 'g',
    category: 'Proteínas',
    isUltraProcessed: false,
    score: 95,
    grade: 'A',
  },
  {
    id: '3',
    name: 'Arroz Integral Cozido',
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.4,
    sodium: 5,
    servingSize: 100,
    servingUnit: 'g',
    category: 'Carboidratos',
    isUltraProcessed: false,
    score: 80,
    grade: 'A',
  },
  {
    id: '4',
    name: 'Ovo Cozido',
    calories: 155,
    protein: 12.6,
    carbs: 1.1,
    fat: 10.6,
    fiber: 0,
    sugar: 1.1,
    sodium: 124,
    servingSize: 100,
    servingUnit: 'g',
    category: 'Proteínas',
    isUltraProcessed: false,
    score: 90,
    grade: 'A',
  },
  {
    id: '5',
    name: 'Batata Doce Cozida',
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    fiber: 3,
    sugar: 4.2,
    sodium: 55,
    servingSize: 100,
    servingUnit: 'g',
    category: 'Carboidratos',
    isUltraProcessed: false,
    score: 85,
    grade: 'A',
  },
  {
    id: '6',
    name: 'Aveia',
    calories: 389,
    protein: 16.9,
    carbs: 66.3,
    fat: 6.9,
    fiber: 10.6,
    sugar: 0.8,
    sodium: 2,
    servingSize: 100,
    servingUnit: 'g',
    category: 'Carboidratos',
    isUltraProcessed: false,
    score: 92,
    grade: 'A',
  },
  {
    id: '7',
    name: 'Refrigerante Cola',
    calories: 42,
    protein: 0,
    carbs: 10.6,
    fat: 0,
    fiber: 0,
    sugar: 10.6,
    sodium: 11,
    servingSize: 100,
    servingUnit: 'ml',
    category: 'Bebidas',
    isUltraProcessed: true,
    score: 15,
    grade: 'E',
  },
  {
    id: '8',
    name: 'Salmão Grelhado',
    calories: 206,
    protein: 22,
    carbs: 0,
    fat: 13,
    fiber: 0,
    sugar: 0,
    sodium: 59,
    servingSize: 100,
    servingUnit: 'g',
    category: 'Proteínas',
    isUltraProcessed: false,
    score: 95,
    grade: 'A',
  },
];

export const mockExercises: Exercise[] = [
  {
    id: 'ex1',
    name: 'Flexão de Braço',
    description: 'Exercício clássico para peito, ombros e tríceps. Mantenha o corpo reto.',
    videoUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    duration: 30,
    sets: 3,
    reps: 12,
    restTime: 60,
    equipment: ['none'],
    muscleGroups: ['Peito', 'Tríceps', 'Ombros'],
    difficulty: 'beginner',
    caloriesBurn: 8,
  },
  {
    id: 'ex2',
    name: 'Agachamento',
    description: 'Exercício fundamental para pernas e glúteos. Mantenha as costas retas.',
    videoUrl: 'https://www.youtube.com/watch?v=aclHkVaku9U',
    duration: 40,
    sets: 3,
    reps: 15,
    restTime: 60,
    equipment: ['none'],
    muscleGroups: ['Pernas', 'Glúteos'],
    difficulty: 'beginner',
    caloriesBurn: 10,
  },
  {
    id: 'ex3',
    name: 'Prancha',
    description: 'Exercício isométrico para core. Mantenha o corpo alinhado.',
    videoUrl: 'https://www.youtube.com/watch?v=pSHjTRCQxIw',
    duration: 45,
    sets: 3,
    reps: 1,
    restTime: 45,
    equipment: ['none'],
    muscleGroups: ['Abdômen', 'Core'],
    difficulty: 'beginner',
    caloriesBurn: 6,
  },
  {
    id: 'ex4',
    name: 'Burpee',
    description: 'Exercício completo de corpo inteiro. Ótimo para cardio.',
    videoUrl: 'https://www.youtube.com/watch?v=dZgVxmf6jkA',
    duration: 30,
    sets: 3,
    reps: 10,
    restTime: 60,
    equipment: ['none'],
    muscleGroups: ['Corpo Inteiro'],
    difficulty: 'intermediate',
    caloriesBurn: 12,
  },
  {
    id: 'ex5',
    name: 'Rosca Direta com Halteres',
    description: 'Exercício isolado para bíceps.',
    videoUrl: 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo',
    duration: 30,
    sets: 3,
    reps: 12,
    restTime: 45,
    equipment: ['dumbbells'],
    muscleGroups: ['Bíceps'],
    difficulty: 'beginner',
    caloriesBurn: 5,
  },
];

export const mockWorkouts: Workout[] = [
  {
    id: 'w1',
    name: 'Treino Full Body Iniciante',
    description: 'Treino completo para iniciantes sem equipamento',
    exercises: [mockExercises[0], mockExercises[1], mockExercises[2]],
    totalDuration: 20,
    difficulty: 'beginner',
    equipment: ['none'],
    caloriesBurn: 150,
    day: 1,
  },
  {
    id: 'w2',
    name: 'Treino HIIT Cardio',
    description: 'Alta intensidade para queimar calorias',
    exercises: [mockExercises[3], mockExercises[1], mockExercises[0]],
    totalDuration: 15,
    difficulty: 'intermediate',
    equipment: ['none'],
    caloriesBurn: 200,
    day: 3,
  },
  {
    id: 'w3',
    name: 'Treino de Força com Halteres',
    description: 'Desenvolvimento muscular com halteres',
    exercises: [mockExercises[4], mockExercises[0], mockExercises[1]],
    totalDuration: 25,
    difficulty: 'intermediate',
    equipment: ['dumbbells'],
    caloriesBurn: 180,
    day: 5,
  },
];

export const mockChallenges: Challenge[] = [
  {
    id: 'c1',
    name: 'Desafio 21 Dias Saudável',
    description: 'Transforme seus hábitos em 21 dias',
    duration: 21,
    tasks: [
      'Beber 2L de água',
      'Completar treino do dia',
      'Registrar todas as refeições',
      'Dormir 7-8 horas',
    ],
    reward: 'Badge Guerreiro da Saúde',
    participants: 1247,
  },
  {
    id: 'c2',
    name: 'Desafio Sem Açúcar',
    description: '7 dias sem açúcar refinado',
    duration: 7,
    tasks: [
      'Zero refrigerante',
      'Zero doces',
      'Ler rótulos',
      'Substituir por frutas',
    ],
    reward: 'Badge Detox Master',
    participants: 892,
  },
];
